---
- name: Install a single node cluster datalake
  hosts: localhost

  tasks:
    - name: install snap package
      apt:
        pkg: snap
      become: yes

    - name: install microk8s
      community.general.snap:
        name: microk8s
        classic: yes
      become: yes

    - name: add user to microk8s group
      ansible.builtin.user:
        name: "{{ lookup('env','USER') }}"
        append: true
        groups: microk8s
      become: yes

    - name: add  helm repositories
      kubernetes.core.helm_repository:
        name:  "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      with_items:
        - name: apache-airflow
          repo_url: https://airflow.apache.org
        - name: trino
          repo_url: https://trinodb.github.io/charts
        - name:  bitnami
          repo_url: https://charts.bitnami.com/bitnami
        - name: minio-operator
          repo_url: https://operator.min.io
        - name: gitea-charts
          repo_url: https://dl.gitea.com/charts/
        - name: harbor
          repo_url: https://helm.goharbor.io